# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [33]:
import torch

random1 = torch.rand(7, 7)

print(random1)



tensor([[0.7865, 0.6604, 0.1303, 0.3498, 0.3824, 0.8043, 0.3186],
        [0.2908, 0.4196, 0.3728, 0.3769, 0.0108, 0.9455, 0.7661],
        [0.2634, 0.1880, 0.5174, 0.7849, 0.1412, 0.3112, 0.7091],
        [0.1775, 0.4443, 0.1230, 0.9638, 0.7695, 0.0378, 0.2239],
        [0.6772, 0.5274, 0.6325, 0.0910, 0.2323, 0.7269, 0.1187],
        [0.3951, 0.7199, 0.7595, 0.5311, 0.6449, 0.7224, 0.4416],
        [0.3634, 0.8818, 0.9874, 0.7316, 0.2814, 0.0651, 0.0065]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [34]:


B = torch.rand(1, 7)


result = torch.matmul(random1, B.T )

print(result)


tensor([[2.0983],
        [1.8557],
        [1.4832],
        [1.5734],
        [1.7670],
        [2.4643],
        [1.4786]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [36]:

torch.manual_seed(0)
random1 = torch.rand(7, 7)
B = torch.rand(1, 7)
result = torch.matmul(random1, B.T )
result


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [37]:
torch.cuda.manual_seed(1234)

6-Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:¶
Device: cuda




(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [38]:
torch.manual_seed(1234)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.rand(2, 3, device=device)
y = torch.rand(2, 3, device=device)
x, y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [39]:
result = torch.matmul(x, y.T)
print(result, result.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [40]:
print(result.max(), result.min())


tensor(0.5617) tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [41]:
print(result.argmax(), result.argmin())


tensor(3) tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [42]:
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
tensor_squeezed = tensor.squeeze()

print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
